# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - modules-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - modules-

      - run: npm i

      - save_cache:
          paths:
            - node_modules
          key: modules-{{ checksum "package.json" }}

      - run: node test

      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish
workflows:
  version: 2
  commit:
    jobs:
      - test
      - deploy:
        requires:
          - test
        filters:
          branches:
            only: master
          tags:
            only: /^v.*/